# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af5aba93d56c59bf9cd2eb356d57c2ef4c12ba7c60db7cff40f6b2ab0c3a6fc005861c2ced278077e17b3258fcf240ed151b44abdeab7665dbe534729788822f

test:
  secret_key_base: 9ce90b4de8437fd28aef70df8223b94e5e0021e95d7245dcf6801071c8335931ed75be73fcfce11cf5ddf41f107d0c50f025c58358724080bd55d61e437a59a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
